// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC7EQ40Y9OhKnrIOe51XhjujlMcitmiA8',
    appId: '1:76774528849:web:b35bc15303c92299e86570',
    messagingSenderId: '76774528849',
    projectId: 'egranth-fac05',
    authDomain: 'egranth-fac05.firebaseapp.com',
    storageBucket: 'egranth-fac05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYHpnU1cSQKebfkU0qSWoiDDwGUvxgPWE',
    appId: '1:76774528849:android:582c99119d69dbe6e86570',
    messagingSenderId: '76774528849',
    projectId: 'egranth-fac05',
    storageBucket: 'egranth-fac05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUyZD3GiQKEsfAM5BsgJX-3vl0i2N2vQ',
    appId: '1:76774528849:ios:13170c13155855e1e86570',
    messagingSenderId: '76774528849',
    projectId: 'egranth-fac05',
    storageBucket: 'egranth-fac05.appspot.com',
    iosClientId: '76774528849-u9iq138r683dj6nghqp0vmjkaju6qk3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.egranth',
  );
}
